FROM alpine:3.5

LABEL maintainer="tian.r.king@gmail.com"
LABEL author="w0x7ce"
LABEL version="v0.1"
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
COPY ./app /code/app

ARG FFMPEG_VERSION=3.3.2

## Just for cn user
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories 
## End

RUN apk update && \
    apk upgrade && \
    apk add --update ca-certificates && \
    apk add ffmpeg
#     apk add --update ca-certificates && \
#     apk add gnutls-dev zlib-dev yasm-dev lame-dev libogg-dev \
#     x264-dev libvpx-dev libvorbis-dev x265-dev freetype-dev \
#     libass-dev libwebp-dev rtmpdump-dev libtheora-dev opus-dev && \
#     apk add --no-cache --virtual .build-dependencies \
#     build-base coreutils tar bzip2 x264 gnutls nasm && \
# # Install ffmpeg
#     wget -O- http://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.gz | tar xzC /tmp && \
#     cd /tmp/ffmpeg-${FFMPEG_VERSION} && \
#     ./configure --bindir="/usr/bin" \
#                 --enable-version3 \
#                 --enable-gpl \
#                 --enable-nonfree \
#                 --enable-small \
#                 --enable-libmp3lame \
#                 --enable-libx264 \
#                 --enable-libx265 \
#                 --enable-libvpx \
#                 --enable-libtheora \
#                 --enable-libvorbis \
#                 --enable-libopus \
#                 --enable-libass \
#                 --enable-libwebp \
#                 --enable-librtmp \
#                 --enable-postproc \
#                 --enable-avresample \
#                 --enable-libfreetype \
#                 --enable-gnutls \
#                 --disable-debug && \
#     make && \
#     make install && \
#     make distclean && \
#     cd $OLDPWD && \
# # Cleanup
#     rm -rf /tmp/ffmpeg-${FFMPEG_VERSION} && \
#     apk del --purge .build-dependencies && \
#     rm -rf /var/cache/apk/*
RUN apk add python3
RUN apk add py3-pip
# RUN pip config set global.index-url http://mirrors.aliyun.com/pypi/simple
# RUN pip config set install.trusted-host mirrors.aliyun.com
# RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
RUN echo "EXPOSE PORT 81 "
CMD ["uvicorn", "app.fast_test:app", "--host", "0.0.0.0", "--port", "81"]


